[package]
name = "topology_concept"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bichannel = "0.0.4"
duplex = "0.16.0"
tokio = "1.28.0"
